### ISSUE TITLE
Upload example please

### ISSUE THREAD

**Issue by suntong** [mehmetcanfarsak/PersonalDrive#1]
Hi, 

I'm reading https://personaldrive.deta.dev/docs#/File%20Upload/upload_publicly_accessible_file_public_file_post and trying to figure out how to do [File Upload](https://personaldrive.deta.dev/docs#/File%20Upload), but was stopped by the 

> Request body of multipart/form-data  
file *  
string($binary)

part. 

Would you give a none-Python example please, or it has to be called within Python? 

thanks for such wonderful open source tool BTW.

**Comment by mehmetcanfarsak** [comment]
Hi,
First of all thank you for using PersonalDrive
since [https://personaldrive.deta.dev/](https://personaldrive.deta.dev/) is just a demo server. You should deploy your instance to deta.sh free account with the link [https://go.deta.dev/deploy?repo=https://github.com/mehmetcanfarsak/PersonalDrive](https://go.deta.dev/deploy?repo=https://github.com/mehmetcanfarsak/PersonalDrive)

If you have any questions please let me know
